<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>voice-switch</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\VoiceSwitch.Windows.Core\VoiceSwitch.Windows.Core.csproj" />
  </ItemGroup>
</Project>
